# Funding options for Alertmanager++

# GitHub Sponsors
# github: [ipiton]

# Open Collective
# open_collective: alertmanager-plus-plus

# Custom funding links
custom: ["https://github.com/sponsors/ipiton"]

