# Automatic labeling for PRs
# https://github.com/actions/labeler

# Documentation
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

# Go code
go:
  - changed-files:
    - any-glob-to-any-file: '**/*.go'

# Tests
tests:
  - changed-files:
    - any-glob-to-any-file: '**/*_test.go'

# CI/CD
ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - 'Makefile'
      - 'Dockerfile'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'go-app/go.mod'
      - 'go-app/go.sum'

# Core
core:
  - changed-files:
    - any-glob-to-any-file: 'pkg/core/**/*'

# Examples
examples:
  - changed-files:
    - any-glob-to-any-file: 'examples/**/*'

# Infrastructure
infrastructure:
  - changed-files:
    - any-glob-to-any-file: 'go-app/internal/infrastructure/**/*'

# Business logic
business:
  - changed-files:
    - any-glob-to-any-file: 'go-app/internal/business/**/*'

# Deployment
deployment:
  - changed-files:
    - any-glob-to-any-file:
      - 'helm/**/*'
      - 'k8s/**/*'
