name: ✨ Feature Request
description: Suggest a new feature for Alertmanager++
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! 🚀

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: I also thought about...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case in detail
      placeholder: |
        In my setup, I have...
        I would use this feature to...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my adoption)
        - High (would use it immediately)
        - Medium (nice to have)
        - Low (future enhancement)
    validations:
      required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Are you willing to contribute?
      description: Would you like to implement this feature?
      options:
        - Yes, I can submit a PR
        - Maybe, with guidance
        - No, but I can help test
        - No, but I can provide feedback
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: Here's a similar feature in another tool...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature aligns with Alertmanager++ goals
          required: true
        - label: I have described the use case clearly
          required: true

