#!/usr/bin/env bash
# Sync the vendored Solo Kanban framework from an upstream checkout.
#
#   scripts/solo-kanban-sync.sh [--allow-dirty] [upstream-dir]
#                                 (default upstream: ~/Documents/Projects/solo-kanban)
#
# Vendored files are upstream copies with one deterministic rewrite: framework
# doc paths (docs/workflow.md, ...) point at docs/solo-kanban/. Never edit them
# by hand -- the next sync overwrites them. AMP-specific rules live in
# WORKFLOW.md (overlay). Files removed upstream are removed here too, but only
# those this script vendored before (listed in docs/solo-kanban/VERSION), so
# local additions such as extra commands are left alone.
#
# Idempotent: a second run on the same upstream commit changes nothing.
set -euo pipefail

ALLOW_DIRTY=0
if [ "${1:-}" = "--allow-dirty" ]; then
  ALLOW_DIRTY=1
  shift
fi
UPSTREAM="${1:-$HOME/Documents/Projects/solo-kanban}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION_FILE="$ROOT/docs/solo-kanban/VERSION"

# A missing source dir would otherwise look like "everything removed upstream"
# and delete the whole vendored set.
for dir in docs agents/claude/commands agents/codex/skills templates/task; do
  if [ ! -d "$UPSTREAM/$dir" ]; then
    echo "error: not a solo-kanban checkout (no $dir/): $UPSTREAM" >&2
    exit 2
  fi
done

version="$(git -C "$UPSTREAM" describe --tags --always)"
commit="$(git -C "$UPSTREAM" rev-parse --short HEAD)"
if [ -n "$(git -C "$UPSTREAM" status --porcelain)" ]; then
  if [ "$ALLOW_DIRTY" -ne 1 ]; then
    echo "error: upstream has uncommitted changes; commit them or pass --allow-dirty" >&2
    exit 2
  fi
  commit="$commit-dirty"
  echo "warning: vendoring a dirty upstream; VERSION records $commit" >&2
fi

rewrite() { # <src> <dst>
  mkdir -p "$(dirname "$2")"
  sed -E 's#docs/(workflow|agent-policies|artifact-contract|method|ai-agent-playbook)\.md#docs/solo-kanban/\1.md#g' \
    "$1" >"$2"
}

previous() { # <key> -> files vendored under <key> by the last sync
  [ -f "$VERSION_FILE" ] || return 0
  sed -n "s/^$1: //p" "$VERSION_FILE" | tr ' ' '\n' | sed '/^$/d'
}

# sync_set <key> <src-dir> <dst-dir> <names...>: vendor <names> (paths relative
# to src-dir), then delete what the last sync vendored under <key> but upstream
# no longer has. Prints the resulting name list.
sync_set() {
  set -e # runs inside $(...), where bash 3.2 drops errexit
  local key="$1" src="$2" dst="$3"
  shift 3
  if [ "$#" -eq 0 ]; then
    echo "error: upstream has no files for '$key'; refusing to delete the vendored set" >&2
    exit 2
  fi
  local name
  for name in "$@"; do
    rewrite "$src/$name" "$dst/$name"
  done
  for name in $(previous "$key"); do
    case "$name" in /* | *..*)
      echo "error: unsafe path in VERSION ($key): $name" >&2
      exit 2
      ;;
    esac
    case " $* " in *" $name "*) ;; *)
      rm -f "$dst/$name"
      rmdir "$(dirname "$dst/$name")" 2>/dev/null || true
      echo "removed (gone upstream): ${dst#"$ROOT"/}/$name" >&2
      ;;
    esac
  done
  echo "$*"
}

names() { # <dir> <find-args...> -> sorted relative paths
  local dir="$1"
  shift
  (cd "$dir" && find . "$@" -type f | sed 's#^\./##' | LC_ALL=C sort | tr '\n' ' ')
}

docs=$(sync_set docs "$UPSTREAM/docs" "$ROOT/docs/solo-kanban" \
  $(names "$UPSTREAM/docs" -maxdepth 1 -name '*.md'))
commands=$(sync_set commands "$UPSTREAM/agents/claude/commands" "$ROOT/.claude/commands" \
  $(names "$UPSTREAM/agents/claude/commands" -maxdepth 1 -name '*.md' ! -name README.md ! -name deploy.md))
skills=$(sync_set skills "$UPSTREAM/agents/codex/skills" "$ROOT/skills" \
  $(names "$UPSTREAM/agents/codex/skills" -name SKILL.md))
templates=$(sync_set templates "$UPSTREAM/templates/task" "$ROOT/tasks/templates" \
  $(names "$UPSTREAM/templates/task" -maxdepth 1 -name '*.md'))

cat >"$VERSION_FILE" <<EOF
# Vendored Solo Kanban framework. Generated by scripts/solo-kanban-sync.sh -- do not edit.
upstream: https://github.com/ipiton/solo-kanban-framework
version: $version
commit: $commit
docs: $docs
commands: $commands
skills: $skills
templates: $templates
EOF

echo "synced Solo Kanban $version ($commit)"
